"""Export a scan's full report as JSON or Markdown."""
from __future__ import annotations

import io
import json

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.routes_scans import get_report
from app.database import get_db

router = APIRouter(prefix="/scans/{scan_id}/export", tags=["export"])


@router.get("/json")
async def export_json(scan_id: str, db: AsyncSession = Depends(get_db)):
    report = await get_report(scan_id, db)
    buffer = io.BytesIO(report.model_dump_json(indent=2).encode())
    return StreamingResponse(
        buffer, media_type="application/json",
        headers={"Content-Disposition": f"attachment; filename=scan_{scan_id}.json"},
    )


@router.get("/markdown")
async def export_markdown(scan_id: str, db: AsyncSession = Depends(get_db)):
    report = await get_report(scan_id, db)
    md = _render_markdown(report)
    buffer = io.BytesIO(md.encode())
    return StreamingResponse(
        buffer, media_type="text/markdown",
        headers={"Content-Disposition": f"attachment; filename=scan_{scan_id}.md"},
    )


def _render_markdown(report) -> str:
    lines = [
        f"# Bug Bounty Copilot Report",
        f"**Scan ID:** {report.scan.id}",
        f"**Status:** {report.scan.status}",
        f"**Attack Surface Risk Score:** {report.risk_score}/100",
        "",
        "## AI Summary",
        report.ai_summary,
        "",
        f"## Subdomains ({len(report.subdomains)})",
        "| Hostname | Alive | Status | Title | WAF/CDN |",
        "|---|---|---|---|---|",
    ]
    for s in report.subdomains:
        lines.append(f"| {s.hostname} | {s.is_alive} | {s.status_code or '-'} | {s.title or '-'} | {s.cdn_or_waf or '-'} |")

    lines += ["", f"## Endpoints ({len(report.endpoints)})", "| URL | Method | Status | API? | Source |", "|---|---|---|---|---|"]
    for e in report.endpoints:
        lines.append(f"| {e.url} | {e.method} | {e.status_code or '-'} | {e.is_api} | {e.source} |")

    lines += ["", f"## Parameters ({len(report.parameters)})", "| Name | Example URL | Hint |", "|---|---|---|"]
    for p in report.parameters:
        lines.append(f"| {p.name} | {p.example_url} | {p.reflected_context or '-'} |")

    lines += ["", f"## Secrets ({len(report.secrets)})", "| Type | Source | Redacted Match | Severity |", "|---|---|---|---|"]
    for sec in report.secrets:
        lines.append(f"| {sec.secret_type} | {sec.source_url} | {sec.match_redacted} | {sec.severity} |")

    lines += ["", f"## Technologies ({len(report.technologies)})", "| Host | Name | Category |", "|---|---|---|"]
    for t in report.technologies:
        lines.append(f"| {t.hostname} | {t.name} | {t.category} |")

    if report.takeover_candidates:
        lines += ["", f"## \u26a0\ufe0f Potential Subdomain Takeovers ({len(report.takeover_candidates)})",
                   "| Hostname | CNAME | Service | Confidence |", "|---|---|---|---|"]
        for tc in report.takeover_candidates:
            lines.append(f"| {tc.hostname} | {tc.cname} | {tc.service} | {tc.confidence} |")
        lines += ["", "*Passive DNS/HTTP signal only -- no resource was claimed or modified. "
                       "Verify manually before taking any action.*"]

    lines += ["", f"## AI Findings / Recommendations ({len(report.findings)})"]
    for f in report.findings:
        lines += [
            f"### {f.vulnerability_class} — Confidence: {f.confidence}",
            f"- **Asset:** {f.related_asset}",
            f"- **Reasoning:** {f.reasoning}",
            f"- **Recommended next step:** {f.recommended_next_step}",
            "",
        ]

    lines += ["", "---", "*This report is a triage aid generated by an assistant tool. It does not confirm "
                       "vulnerabilities and no exploitation was performed. All items require manual verification "
                       "by an authorized human researcher before disclosure.*"]
    return "\n".join(lines)
